/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as SupportRouteImport } from './routes/support'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as EarnMoreRouteImport } from './routes/earn-more'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuyMpayRouteImport } from './routes/buy-mpay'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnMoreRoute = EarnMoreRouteImport.update({
  id: '/earn-more',
  path: '/earn-more',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyMpayRoute = BuyMpayRouteImport.update({
  id: '/buy-mpay',
  path: '/buy-mpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/buy-mpay': typeof BuyMpayRoute
  '/dashboard': typeof DashboardRoute
  '/earn-more': typeof EarnMoreRoute
  '/loading': typeof LoadingRoute
  '/notifications': typeof NotificationsRoute
  '/support': typeof SupportRoute
  '/transfer': typeof TransferRoute
  '/welcome': typeof WelcomeRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/buy-mpay': typeof BuyMpayRoute
  '/dashboard': typeof DashboardRoute
  '/earn-more': typeof EarnMoreRoute
  '/loading': typeof LoadingRoute
  '/notifications': typeof NotificationsRoute
  '/support': typeof SupportRoute
  '/transfer': typeof TransferRoute
  '/welcome': typeof WelcomeRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/buy-mpay': typeof BuyMpayRoute
  '/dashboard': typeof DashboardRoute
  '/earn-more': typeof EarnMoreRoute
  '/loading': typeof LoadingRoute
  '/notifications': typeof NotificationsRoute
  '/support': typeof SupportRoute
  '/transfer': typeof TransferRoute
  '/welcome': typeof WelcomeRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/buy-mpay'
    | '/dashboard'
    | '/earn-more'
    | '/loading'
    | '/notifications'
    | '/support'
    | '/transfer'
    | '/welcome'
    | '/service/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/buy-mpay'
    | '/dashboard'
    | '/earn-more'
    | '/loading'
    | '/notifications'
    | '/support'
    | '/transfer'
    | '/welcome'
    | '/service/$slug'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/buy-mpay'
    | '/dashboard'
    | '/earn-more'
    | '/loading'
    | '/notifications'
    | '/support'
    | '/transfer'
    | '/welcome'
    | '/service/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  BuyMpayRoute: typeof BuyMpayRoute
  DashboardRoute: typeof DashboardRoute
  EarnMoreRoute: typeof EarnMoreRoute
  LoadingRoute: typeof LoadingRoute
  NotificationsRoute: typeof NotificationsRoute
  SupportRoute: typeof SupportRoute
  TransferRoute: typeof TransferRoute
  WelcomeRoute: typeof WelcomeRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn-more': {
      id: '/earn-more'
      path: '/earn-more'
      fullPath: '/earn-more'
      preLoaderRoute: typeof EarnMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-mpay': {
      id: '/buy-mpay'
      path: '/buy-mpay'
      fullPath: '/buy-mpay'
      preLoaderRoute: typeof BuyMpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  BuyMpayRoute: BuyMpayRoute,
  DashboardRoute: DashboardRoute,
  EarnMoreRoute: EarnMoreRoute,
  LoadingRoute: LoadingRoute,
  NotificationsRoute: NotificationsRoute,
  SupportRoute: SupportRoute,
  TransferRoute: TransferRoute,
  WelcomeRoute: WelcomeRoute,
  ServiceSlugRoute: ServiceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
